spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:MagicAlbum}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=utf8
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:04126}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  flyway:
    locations: classpath:db/migration/mysql